series: Intermediate C++
title: Macros
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Macros are really cool, but they can also be easily misused.
language: C++
tags:
  - Core
extra_resources:
    link: http://stackoverflow.com/questions/14041453/why-are-preprocessor-macros-evil-and-what-are-the-alternatives
    title: The Evils of Macros
connections:
  - series: Intermediate C++
    title: Enums